Backend/MusicWeb/MusicWeb/Models/Domain/Genre.cs
using System.ComponentModel.DataAnnotations;

namespace MusicWeb.Models.Domain
{
    public class Genre
    {
        [Key]
        public int GenreId { get; set; }
        [Required]
        public string GenreName { get; set; }

    }
}

Backend/MusicWeb/MusicWeb/Controllers/GenresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MusicWeb.Models.Domain;

namespace MusicWeb.Controllers
{
    public class GenresController : Controller
    {
        private readonly DatabaseContext _context;

        public GenresController(DatabaseContext context)
        {
            _context = context;
        }

        // GET: Genres/GetGenre
        public async Task<IActionResult> GetGenre()
        {
            List<Genre> genres = await _context.Genre.ToListAsync();
            return View(genres);
        }

        // Post: Seatch to Songs
        [HttpGet("Search")]
        public async Task<IActionResult> Search(int GenreId)
        {
            List<Songs> songs = await _context.Songs.ToListAsync();
            List<Songs> dataSearch = new List<Songs>();
            foreach (var item in songs)
            {
                if (item.GenreId == GenreId)
                {
                    dataSearch.Add(item);
                }
            }
            return View(dataSearch);
        }

        // GET: Genres
        public async Task<IActionResult> Index()
        {
              return _context.Genre != null ? 
                          View(await _context.Genre.ToListAsync()) :
                          Problem("Entity set 'DatabaseContext.Genre'  is null.");
        }

        // GET: Genres/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Genre == null)
            {
                return NotFound();
            }

            var genre = await _context.Genre
                .FirstOrDefaultAsync(m => m.GenreId == id);
            if (genre == null)
            {
                return NotFound();
            }

            return View(genre);
        }

        // GET: Genres/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Genres/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("GenreId,GenreName")] Genre genre)
        {
            if (ModelState.IsValid)
            {
                _context.Add(genre);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(genre);
        }

        // GET: Genres/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Genre == null)
            {
                return NotFound();
            }

            var genre = await _context.Genre.FindAsync(id);
            if (genre == null)
            {
                return NotFound();
            }
            return View(genre);
        }

        // POST: Genres/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("GenreId,GenreName")] Genre genre)
        {
            if (id != genre.GenreId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(genre);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GenreExists(genre.GenreId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(genre);
        }

        // GET: Genres/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Genre == null)
            {
                return NotFound();
            }

            var genre = await _context.Genre
                .FirstOrDefaultAsync(m => m.GenreId == id);
            if (genre == null)
            {
                return NotFound();
            }

            return View(genre);
        }

        // POST: Genres/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Genre == null)
            {
                return Problem("Entity set 'DatabaseContext.Genre'  is null.");
            }
            var genre = await _context.Genre.FindAsync(id);
            if (genre != null)
            {
                _context.Genre.Remove(genre);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GenreExists(int id)
        {
          return (_context.Genre?.Any(e => e.GenreId == id)).GetValueOrDefault();
        }
    }
}

Backend/MusicWeb/MusicWeb/Controllers/SongsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MusicWeb.Models.Domain;
using MusicWeb.Models.DTO;

namespace MusicWeb.Controllers
{
    public class SongsController : Controller
    {
        private readonly DatabaseContext _context;

        public SongsController(DatabaseContext context)
        {
            _context = context;
        }

        // GET: Songs/Create
        public async Task<IActionResult> MusicPlay(int id)
        {
            int songId = id;
            var songs = await _context.Songs
                .FirstOrDefaultAsync(m => m.SongId == songId);
            return View(songs);
        }

        // GET: Songs
        public async Task<IActionResult> Index()
        {
              return _context.Songs != null ? 
                          View(await _context.Songs.ToListAsync()) :
                          Problem("Entity set 'DatabaseContext.Songs'  is null.");
        }



        // Post: Seatch to Songs
        [HttpPost]
        public async Task<IActionResult> Search()
        {
            var searchName = Request.Form["searchName"].ToString();
            List<Songs> songs = await _context.Songs.ToListAsync();
            List<Songs> dataSearch = new List<Songs>();
            foreach (var item in songs)
            {
                if(item.SongName.Contains(searchName))
                {
                    dataSearch.Add(item);
                }
            }
            return View(dataSearch);
        }

        // GET: Songs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Songs == null)
            {
                return NotFound();
            }

            var songs = await _context.Songs
                .FirstOrDefaultAsync(m => m.SongId == id);
            if (songs == null)
            {
                return NotFound();
            }
            return View(songs);
        }
        [Authorize(Roles = "admin")]
        // GET: Songs/Create
        public async Task<IActionResult> Create()
        {
            SongsDTO songsDTO = new SongsDTO();
            List<Genre> genres = await _context.Genre.ToListAsync();
            Songs songs = new Songs();
            songsDTO.Songs = songs;
            songsDTO.Genres = genres;
            return View(songsDTO);
        }

        // POST: Songs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Title,SongName,Rate,LinkLocal,LinkImg,Lyric")] Songs songs)
        {
            var linkLocal = songs.LinkLocal;
            songs.LinkLocal = "/data/audio/" + linkLocal+ ".mp3";
            songs.LinkImg = "/data/img/" + linkLocal+ ".jpg";
            if (ModelState.IsValid)
            {
                _context.Add(songs);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(songs);
        }
        [Authorize(Roles = "admin")]
        // GET: Songs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Songs == null)
            {
                return NotFound();
            }

            var songs = await _context.Songs.FindAsync(id);
            if (songs == null)
            {
                return NotFound();
            }
            return View(songs);
        }

        // POST: Songs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("SongId,Title,SongName,Rate,LinkLocal,LinkImg,Lyric")] Songs songs)
        {
            if (id != songs.SongId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(songs);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SongsExists(songs.SongId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(songs);
        }
        [Authorize(Roles = "admin")]
        // GET: Songs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Songs == null)
            {
                return NotFound();
            }

            var songs = await _context.Songs
                .FirstOrDefaultAsync(m => m.SongId == id);
            if (songs == null)
            {
                return NotFound();
            }

            return View(songs);
        }
        [Authorize(Roles = "admin")]
        // POST: Songs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Songs == null)
            {
                return Problem("Entity set 'DatabaseContext.Songs'  is null.");
            }
            var songs = await _context.Songs.FindAsync(id);
            if (songs != null)
            {
                _context.Songs.Remove(songs);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SongsExists(int id)
        {
          return (_context.Songs?.Any(e => e.SongId == id)).GetValueOrDefault();
        }


    }
}

Backend/MusicWeb/MusicWeb/Views/Genres/Create.cshtml
@model MusicWeb.Models.Domain.Genre

@{
    ViewData["Title"] = "Create";
}
<header>
    <style>
        .title {
            display: flex;
            justify-content: center; /* Căn giữa theo chiều ngang */
        }
    </style>
</header>
<h1 class="title">Thêm thể loại nhạc</h1>

<h4 class="title">Thể loại nhạc</h4>
<hr />
<div class="row title">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="GenreName" class="control-label"></label>
                <input asp-for="GenreName" class="form-control" />
                <span asp-validation-for="GenreName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div class="title">
    <a asp-action="Index">Danh sách thể loại nhạc</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Backend/MusicWeb/MusicWeb/Views/Genres/Delete.cshtml
@model MusicWeb.Models.Domain.Genre

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Genre</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GenreName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GenreName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="GenreId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Backend/MusicWeb/MusicWeb/Views/Genres/Details.cshtml
@model MusicWeb.Models.Domain.Genre

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Genre</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GenreName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GenreName)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.GenreId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Backend/MusicWeb/MusicWeb/Views/Genres/Edit.cshtml
@model MusicWeb.Models.Domain.Genre

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Genre</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="GenreId" />
            <div class="form-group">
                <label asp-for="GenreName" class="control-label"></label>
                <input asp-for="GenreName" class="form-control" />
                <span asp-validation-for="GenreName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Backend/MusicWeb/MusicWeb/Views/Genres/GetGenre.cshtml
@model List<MusicWeb.Models.Domain.Genre>
@{

}
<h3>Nghe nhạc theo thể loại:</h3>
<div class="row">
@foreach(var item in Model)
{
    

        <div class="col-sm-6">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Thể loại: @item.GenreName</h5>
                    <a asp-controller="Genres" asp-action="Search" asp-route-id="@item.GenreId" class="btn btn-primary">Danh sách bài hát</a>
                </div>
            </div>
        </div>

}
</div>

Backend/MusicWeb/MusicWeb/Views/Genres/Index.cshtml
@model IEnumerable<MusicWeb.Models.Domain.Genre>

@{
    ViewData["Title"] = "Index";
}
<header>
    <style>
        .title {
            display: flex;
            justify-content: center; /* Căn giữa theo chiều ngang */
        }
    </style>
</header>
<h1 class="title">Danh sách thể loại nhạc</h1>

<p>
    <a asp-action="Create">Thêm mới</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Thể loại nhạc
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.GenreName)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.GenreId">Chỉnh sửa</a> |
                <a asp-action="Details" asp-route-id="@item.GenreId">Chi tiết</a> |
                <a asp-action="Delete" asp-route-id="@item.GenreId">Xóa</a>
            </td>
        </tr>
}
    </tbody>
</table>

Backend/MusicWeb/MusicWeb/Views/Genres/Search.cshtml
@model List<MusicWeb.Models.Domain.Songs>
@{

}
<link href="/css/MusicItem.css" rel="stylesheet">
<div class="container mt-2">
    <div class="row">
        @{
            int count = 0;
        }

        @foreach (var item in Model)
        {
            if (count <= 7)
            {
                <div class="col-md-3 col-sm-6">
                    <div class="card card-block" style="margin-top: 10px !important" style="margin-top: 10px !important">
                        <h4 class="card-title text-right">@item.SongName</h4>
                        <img src="@item.LinkImg" alt="Photo of sunset">
                        <h5 class="card-title mt-3 mb-3">@item.Title</h5>
                        <a asp-controller="Songs" asp-action="MusicPlay" asp-route-id="@item.SongId">Lắng nghe bài hát</a>
                    </div>
                </div>
            }
            count++;
        }
    </div>

</div>