Backend/MusicWeb/MusicWeb/Controllers/FavouritesSongsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MusicWeb.Models.Domain;
using MusicWeb.Models.DTO;
using MusicWeb.Repositories.Implementation;

namespace MusicWeb.Controllers
{
    public class FavouritesSongsController : Controller
    {
        private readonly DatabaseContext _context;
        private readonly FavouriteSongsService _favouriteSongsService;
        public FavouritesSongsController(DatabaseContext context, FavouriteSongsService favouriteSongsService)
        {
            _context = context;
            _favouriteSongsService = favouriteSongsService;
        }

        // GET: FavouritesSongs
        public async Task<IActionResult> Index()
        {
            string username = HttpContext.Request.Query["username"];
            FavouriteSongsModel favouriteSongsModel = new FavouriteSongsModel();
            favouriteSongsModel.UserName = username;
            favouriteSongsModel.songs = new List<Songs>();
            var listFavourites = await _context.FavouritesSongs.ToListAsync();
            foreach (var item in listFavourites)
            {
                if(username == item.UserName)
                {
                    var song = await _context.Songs.FindAsync(item.SongId);
                    favouriteSongsModel.songs.Add(song);
                }
            }

            return View(favouriteSongsModel);
        }

        // GET: FavouritesSongs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.FavouritesSongs == null)
            {
                return NotFound();
            }

            var favouritesSongs = await _context.FavouritesSongs
                .FirstOrDefaultAsync(m => m.FavoritesId == id);
            if (favouritesSongs == null)
            {
                return NotFound();
            }

            return View(favouritesSongs);
        }

        // GET: FavouritesSongs/Create
        public IActionResult Create()
        {
            return View();
        }

        public async Task<IActionResult> CreateNew(int id)
        {
            FavouritesSongs save = new FavouritesSongs();
            FavouritesSongs lastInstance = await _favouriteSongsService.GetLastInstanceAnsyc();
            var userName = HttpContext.Request.Query["username"];

            save.SongId = id;
            save.UserName = userName;
            if (ModelState.IsValid)
            {
                _context.Add(save);
                await _context.SaveChangesAsync();
                return NoContent();
            }
            return NoContent();
        }

        // POST: FavouritesSongs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("SongId,UserName")] FavouritesSongs favouritesSongs)
        {
            FavouritesSongs lastInstance = await _favouriteSongsService.GetLastInstanceAnsyc();
            favouritesSongs.FavoritesId = lastInstance.FavoritesId + 1;
            if (ModelState.IsValid)
            {
                _context.Add(favouritesSongs);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(favouritesSongs);
        }

        // GET: FavouritesSongs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.FavouritesSongs == null)
            {
                return NotFound();
            }

            var favouritesSongs = await _context.FavouritesSongs.FindAsync(id);
            if (favouritesSongs == null)
            {
                return NotFound();
            }
            return View(favouritesSongs);
        }


        // POST: FavouritesSongs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("FavoritesId,SongId,UserName")] FavouritesSongs favouritesSongs)
        {
            if (id != favouritesSongs.FavoritesId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(favouritesSongs);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FavouritesSongsExists(favouritesSongs.FavoritesId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(favouritesSongs);
        }

        // GET: FavouritesSongs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.FavouritesSongs == null)
            {
                return NotFound();
            }

            var favouritesSongs = await _context.FavouritesSongs
                .FirstOrDefaultAsync(m => m.FavoritesId == id);
            if (favouritesSongs == null)
            {
                return NotFound();
            }

            return View(favouritesSongs);
        }

        // POST: FavouritesSongs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.FavouritesSongs == null)
            {
                return Problem("Entity set 'DatabaseContext.FavouritesSongs'  is null.");
            }
            var favouritesSongs = await _context.FavouritesSongs.FindAsync(id);
            if (favouritesSongs != null)
            {
                _context.FavouritesSongs.Remove(favouritesSongs);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FavouritesSongsExists(int id)
        {
          return (_context.FavouritesSongs?.Any(e => e.FavoritesId == id)).GetValueOrDefault();
        }
    }
}

Backend/MusicWeb/MusicWeb/Controllers/GenresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MusicWeb.Models.Domain;

namespace MusicWeb.Controllers
{
    public class GenresController : Controller
    {
        private readonly DatabaseContext _context;

        public GenresController(DatabaseContext context)
        {
            _context = context;
        }

        // GET: Genres/GetGenre
        public async Task<IActionResult> GetGenre()
        {
            List<Genre> genres = await _context.Genre.ToListAsync();
            return View(genres);
        }

        // Post: Seatch to Songs
        [HttpGet("Search")]
        public async Task<IActionResult> Search(int GenreId)
        {
            List<Songs> songs = await _context.Songs.ToListAsync();
            List<Songs> dataSearch = new List<Songs>();
            foreach (var item in songs)
            {
                if (item.GenreId == GenreId)
                {
                    dataSearch.Add(item);
                }
            }
            return View(dataSearch);
        }

        // GET: Genres
        public async Task<IActionResult> Index()
        {
              return _context.Genre != null ? 
                          View(await _context.Genre.ToListAsync()) :
                          Problem("Entity set 'DatabaseContext.Genre'  is null.");
        }

        // GET: Genres/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Genre == null)
            {
                return NotFound();
            }

            var genre = await _context.Genre
                .FirstOrDefaultAsync(m => m.GenreId == id);
            if (genre == null)
            {
                return NotFound();
            }

            return View(genre);
        }

        // GET: Genres/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Genres/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("GenreId,GenreName")] Genre genre)
        {
            if (ModelState.IsValid)
            {
                _context.Add(genre);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(genre);
        }

        // GET: Genres/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Genre == null)
            {
                return NotFound();
            }

            var genre = await _context.Genre.FindAsync(id);
            if (genre == null)
            {
                return NotFound();
            }
            return View(genre);
        }

        // POST: Genres/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("GenreId,GenreName")] Genre genre)
        {
            if (id != genre.GenreId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(genre);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GenreExists(genre.GenreId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(genre);
        }

        // GET: Genres/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Genre == null)
            {
                return NotFound();
            }

            var genre = await _context.Genre
                .FirstOrDefaultAsync(m => m.GenreId == id);
            if (genre == null)
            {
                return NotFound();
            }

            return View(genre);
        }

        // POST: Genres/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Genre == null)
            {
                return Problem("Entity set 'DatabaseContext.Genre'  is null.");
            }
            var genre = await _context.Genre.FindAsync(id);
            if (genre != null)
            {
                _context.Genre.Remove(genre);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GenreExists(int id)
        {
          return (_context.Genre?.Any(e => e.GenreId == id)).GetValueOrDefault();
        }
    }
}

Backend/MusicWeb/MusicWeb/Views/Shared/Components/Navbar/Default.cshtml
@{
    string name = User.Identity.Name;
    string role = User.IsInRole("admin") ? "admin" : "user";
}
<!-- BOOTSTRAP STYLES-->
<!-- Sidebar -->
<ul class="navbar-nav bg-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="#">
        <div class="sidebar-brand-icon rotate-n-15">
            <i class="fas fa-laugh-wink"></i>
        </div>
        <div class="sidebar-brand-text mx-3">@name<sup>@role</sup></div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Dashboard -->
    <li class="nav-item active">
        <a class="nav-link" href="/Dashboard/Display">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>TRANG CHỦ</span>
        </a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
        ALBUM CỦA TÔI
    </div>

    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"
           aria-expanded="true" aria-controls="collapseTwo">
            <i class="fas fa-fw fa-cog"></i>
            <span>DANH SÁCH</span>
        </a>
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <a class="collapse-item" asp-controller="FavouritesSongs" asp-route-username="@name" asp-action="Index">YÊU THÍCH</a>
            </div>
        </div>
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <a class="collapse-item" asp-controller="Genres" asp-action="GetGenre">THỂ LOẠI NHẠC</a>
            </div>
        </div>
    </li>

    @if (User.IsInRole("admin"))
    {
        <li class="nav-item active">
            <a class="nav-link" href="/Admin/Display">
                <i class="fas fa-fw fa-tachometer-alt"></i>
                <span>Admin Page</span>
            </a>
        </li>
        <li class="nav-item active">
            <a class="nav-link" href="/Songs/Create">
                <i class="fas fa-fw fa-tachometer-alt"></i>
                <span>QL BÀI HÁT</span>
            </a>
        </li>
        <li class="nav-item active">
            <a class="nav-link" href="/Admin/ListUser">
                <i class="fas fa-fw fa-tachometer-alt"></i>
                <span>QL NGƯỜI DÙNG</span>
            </a>
        </li>
        <li class="nav-item active">
            <a class="nav-link" href="/Genres/Index">
                <i class="fas fa-fw fa-tachometer-alt"></i>
                <span>THỂ LOẠI BÀI HÁT</span>
            </a>
        </li>
    }

    
    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block">

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>


</ul>
<!-- End of Sidebar -->